### ISSUE TITLE
[TOKEN REQUEST]: Add FYH

### ISSUE THREAD

**Issue by fuyohasia** [tallyhowallet/token-list#54]
### Contact Details

fuyohasia@gmail.com

### Token Name

FuYoH

### Chain Id

137

### Token Symbol

FYH

### Decimals

9

### Contract Address

0x0d450bf37Ec899cCA90ede124b3E69C9Ae2F2F1C

### Image Link

https://raw.githubusercontent.com/fuyohasia/official-logo/main/FYH-POLYGON-LOGO/FYH-POLYGON-20-2022-LOGO-512x512.png

### Other Information?

ASIA Meme Toke Project - A Fun token for the community and long-term benefit for holders. Focus on Trading, Community Events, Asia Meme NFT and Games.

### Have you verified that the token does not already exist on the Tally Ho token list or any of the other token lists we aggregate?

- [X] I agree the token is not on the token list already.

**Comment by mhluongo** [comment]
Closed by #78
