### ISSUE TITLE
[TOKEN REQUEST]: rETH Arbitrum

### ISSUE THREAD

**Issue by morisschulzersson** [tallyhowallet/token-list#55]
### Contact Details

0xMosson (🐶,🦎)#2629

### Token Name

Rocket Pool ETH

### Chain Id

42161

### Token Symbol

rETH

### Decimals

18

### Contract Address

0xEC70Dcb4A1EFa46b8F2D97C310C9c4790ba5ffA8

### Image Link

https://github.com/MetaMask/contract-metadata/blob/master/images/rETH.svg

### Other Information?

The only decentralized LSD

### Have you verified that the token does not already exist on the Tally Ho token list or any of the other token lists we aggregate?

- [X] I agree the token is not on the token list already.

**Comment by mhluongo** [comment]
Closed by #78
