### ISSUE TITLE
[TOKEN REQUEST]: rETH Optimism

### ISSUE THREAD

**Issue by morisschulzersson** [tallyhowallet/token-list#56]
### Contact Details

0xMosson (🐶,🦎)#2629

### Token Name

Rocket Pool ETH

### Chain Id

10

### Token Symbol

rETH

### Decimals

18

### Contract Address

0x9bcef72be871e61ed4fbbc7630889bee758eb81d

### Image Link

https://github.com/MetaMask/contract-metadata/blob/master/images/rETH.svg

### Other Information?

The only decentralized LSD

### Have you verified that the token does not already exist on the Tally Ho token list or any of the other token lists we aggregate?

- [X] I agree the token is not on the token list already.

**Comment by mhluongo** [comment]
Closed by #78
