### ISSUE TITLE
[TOKEN REQUEST]: rETH Polygon

### ISSUE THREAD

**Issue by morisschulzersson** [tallyhowallet/token-list#57]
### Contact Details

0xMosson (🐶,🦎)#2629

### Token Name

Rocket Pool ETH

### Chain Id

137

### Token Symbol

rETH

### Decimals

18

### Contract Address

0x0266F4F08D82372CF0FcbCCc0Ff74309089c74d1

### Image Link

https://github.com/MetaMask/contract-metadata/blob/master/images/rETH.svg

### Other Information?

The only decentralized LSD

### Have you verified that the token does not already exist on the Tally Ho token list or any of the other token lists we aggregate?

- [X] I agree the token is not on the token list already.

**Comment by mhluongo** [comment]
Closed by #78
