### ISSUE TITLE
[TOKEN REQUEST]: RPL

### ISSUE THREAD

**Issue by morisschulzersson** [tallyhowallet/token-list#58]
### Contact Details

0xMosson (🐶,🦎)#2629

### Token Name

Rocket Pool

### Chain Id

1

### Token Symbol

RPL

### Decimals

18

### Contract Address

0xD33526068D116cE69F19A9ee46F0bd304F21A51f

### Image Link

https://github.com/MetaMask/contract-metadata/blob/master/images/rpl.svg

### Other Information?

This token rocks!

### Have you verified that the token does not already exist on the Tally Ho token list or any of the other token lists we aggregate?

- [X] I agree the token is not on the token list already.

**Comment by 0xzoz** [comment]
This is already completed and can be closed.
