### ISSUE TITLE
[TOKEN REQUEST]: HFT

### ISSUE THREAD

**Issue by otomarukanta** [tallyhowallet/token-list#60]
### Contact Details

5000e12#5000

### Token Name

Hashflow

### Chain Id

1

### Token Symbol

HFT

### Decimals

18

### Contract Address

0xb3999f658c0391d94a37f7ff328f3fec942bcadc

### Image Link

https://assets.coingecko.com/coins/images/26136/small/M4iXwrNz_400x400.jpg

### Other Information?

This token rocks!

### Have you verified that the token does not already exist on the Tally Ho token list or any of the other token lists we aggregate?

- [X] I agree the token is not on the token list already.

**Comment by otomarukanta** [comment]
Open PR https://github.com/tallycash/token-list/pull/61

**Comment by mhluongo** [comment]
Closed by #78
