### ISSUE TITLE
Add RocketPool RPL

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/token-list#65]
### Contact Details

nax

### Token Name

Rocket Pool

### Chain Id

1

### Token Symbol

RPL

### Decimals

18

### Contract Address

0xd33526068d116ce69f19a9ee46f0bd304f21a51f

### Image Link

https://assets.coingecko.com/coins/images/2090/small/rocket_pool_%28RPL%29.png?1637662441

### Other Information?

This token rocks!

### Have you verified that the token does not already exist on the Tally Ho token list or any of the other token lists we aggregate?

- [X] I agree the token is not on the token list already.

**Comment by mhluongo** [comment]
Closed by #78
