### ISSUE TITLE
[TOKEN REQUEST]: NUM

### ISSUE THREAD

**Issue by 43z708** [tallyhowallet/token-list#68]
### Contact Details

kiyo#8414

### Token Name

NUM Token

### Chain Id

1

### Token Symbol

NUM

### Decimals

18

### Contract Address

0x3496b523e5c00a4b4150d6721320cddb234c3079

### Image Link

https://assets.coingecko.com/coins/images/20495/small/NP_Social_media_profile_pic.png?1664026542

### Other Information?

This token rocks!
This is a NumbersProtocol token funded by Binance.

### Have you verified that the token does not already exist on the Tally Ho token list or any of the other token lists we aggregate?

- [X] I agree the token is not on the token list already.

**Comment by mhluongo** [comment]
Closed by #78
