### ISSUE TITLE
Add ETH-BTC Momentum token

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/token-list#70]
### Contact Details

cyberdelic_chimp#9837

### Token Name

ETH-BTC Momentum

### Chain Id

1

### Token Symbol

ETHBTCMom

### Decimals

18

### Contract Address

0x6E2dAc3b9E9ADc0CbbaE2D0B9Fd81952a8D33872

### Other Information?

This token rocks!

### Have you verified that the token does not already exist on the Tally Ho token list or any of the other token lists we aggregate?

- [X] I agree the token is not on the token list already.

**Comment by mhluongo** [comment]
Closed by #78
