### ISSUE TITLE
Add ETH-BTC Trend token

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/token-list#71]
### Contact Details

cyberdelic_chimp#9837

### Token Name

  ETH-BTC Trend 

### Chain Id

1

### Token Symbol

ETHBTCTrend

### Decimals

18

### Contract Address

0x6b7f87279982d919Bbf85182DDeAB179B366D8f2

### Other Information?

-

### Have you verified that the token does not already exist on the Tally Ho token list or any of the other token lists we aggregate?

- [X] I agree the token is not on the token list already.

**Comment by mhluongo** [comment]
Closed by #78
