### ISSUE TITLE
[TOKEN REQUEST]: Staked SPORK

### ISSUE THREAD

**Issue by beemeeupnow** [tallyhowallet/token-list#73]
### Token Name

Staked SPORK

### Chain Id

137

### Token Symbol

sSPORK

### Decimals

18

### Contract Address

0x9C2A7aC762ea6E33cfc380A5C802919b496c9e44

### Image Link

https://uploads-ssl.webflow.com/60caacffe4377fe8cf69a117/60caad3ed066835fc2f70809_SPORKDAO_holo-256x256.png

### Other Information?

Staked SPORK token for SporkDAO

alternate image if needed: https://assets.coingecko.com/coins/images/23358/small/sporkdao.PNG?1643942687

### Have you verified that the token does not already exist on the Tally Ho token list or any of the other token lists we aggregate?

- [X] I agree the token is not on the token list already.

**Comment by mhluongo** [comment]
Closed by #78
