### ISSUE TITLE
[TOKEN REQUEST]: HOP

### ISSUE THREAD

**Issue by zfarhad** [tallyhowallet/token-list#77]
### Contact Details

zfarhad2000@yahoo.com

### Token Name

Hop Protocol

### Chain Id

10

### Token Symbol

HOP

### Decimals

18

### Contract Address

0xc5102fE9359FD9a28f877a67E36B0F050d81a3CC

### Image Link

https://assets.coingecko.com/coins/images/25445/small/hop.png?1665541677

### Other Information?

Hop Protocol is a blockchain bridge protocol that allows users to move tokens from one chain to another without having to wait for a challenge period.

### Have you verified that the token does not already exist on the Tally Ho token list or any of the other token lists we aggregate?

- [X] I agree the token is not on the token list already.

**Comment by mhluongo** [comment]
Closed by #78
